#!/usr/bin/env python3
""" Yams """

import sys
from combi import pair, three, four, full, straight, yams


def print_help(ret):
    """ Displays help """

    print("""
USAGE
        ./201yams d1 d2 d3 d4 d5 c

DESCRIPTION
        d1      value of the first die (0 if not thrown)
        d2      value of the second die (0 if not thrown)
        d3      value of the third die (0 if not thrown)
        d4      value of the fourth die (0 if not thrown)
        d5      value of the fifth die (0 if not thrown)
        c       expected combination""")
    return ret


def check_dices(dices):
    """ Checks value of dices """

    for dice in dices:
        if int(dice) > 6:
            return 84
    return 0


def check_args(argv):
    """ Check args validity """

    if "-h" in argv:
        exit(print_help(0))
    if len(argv) != 6:
        print("Error: ----", file=sys.stderr)
        exit(84)

    dices = []
    for arg in argv:
        dices.append(arg)

    combinaison = argv[5].split("_")
    if combinaison[0] not in OPTIONS.keys():
        print("Error: -----", file=sys.stderr)
        exit(84)

    return dices[:-1], combinaison


def game_yams(argv):
    """ Yams main function """

    dices, combinaison = check_args(argv[1:])

    if check_dices(dices) == 84:
        return 84
    combinaison = argv[6].split("_")
    return OPTIONS[combinaison[0]](combinaison, dices)


if __name__ == "__main__":
    OPTIONS = {
        "pair": pair,
        "three": three,
        "four": four,
        "full": full,
        "straight": straight,
        "yams": yams
    }
    exit(game_yams(sys.argv))
